import { Box, Container } from "@mui/material";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <Box sx={{ bgcolor: "#FBF7F4", height: "98vh" }}>
      <Head>
        <title>Lobby</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <h1>
          Welcome to <a href="https://nextjs.org">Lobby</a>
        </h1>
      </Box>
    </Box>
  );
}
