import { Box, Container, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { colors } from "../styles/colors";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <Box
      sx={{
        backgroundColor: colors.dark.background,
        height: "93vh",
        display: "grid",
        alignContent: "center",
      }}
    >
      <Container
        maxWidth={"xl"}
        sx={{
          backgroundColor: colors.dark.dark1,
          height: "50vh",
          borderRadius: "2rem",
        }}
      >
        <Head>
          <title>Lobby</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Typography variant="h4" color={"secondary"}>
            Welcome to Lobby
          </Typography>
        </main>
      </Container>
    </Box>
  );
}
